### ISSUE TITLE
Link error when building luasocket for Windows

### ISSUE THREAD

**Issue by dalange** [diegonehab/luasocket#109]
options.c.obj : error LNK2019: unresolved external symbol _inet_pton referenced in function _opt_ip6_setmembership
socket.dll : fatal error LNK1120: 1 unresolved externals

According to MSDN reference, inet_pton is only available from Vista and above:
http://msdn.microsoft.com/en-us/library/windows/desktop/cc805844(v=vs.85).aspx

**Comment by sonoro1234** [comment]
LUASOCKET_INET_PTON was necesary for me on msvc2017 with windows7

**Comment by ewestbrook** [comment]
Is there a way we can use a conditional macro or other test to do the right thing automatically?

**Comment by sonoro1234** [comment]
> Is there a way we can use a conditional macro or other test to do the right thing automatically?

what should be the right thing?

**Comment by ewestbrook** [comment]
> what should be the right thing?

Use it when it is necessary to compile.  I do not think I understand exactly what that set of cases is.

**Comment by diegonehab** [comment]
I'm working on building for Windows. Already tested the makefile. Working on the projects. Will have something soon.

**Comment by diegonehab** [comment]
Can you take a look at branch vc14? I updated the makefiles and the project files. Managed to compile and test in both cases. Using Visual Studio 2017. Don't think I needed LUASOCKET_INET_PTON.

**Comment by sonoro1234** [comment]
How should I compile with nmake?

**Comment by diegonehab** [comment]
You can ask for visual studio to retarget the projects, so at least it would compile. 

For the makefile, you should take a look at the vc64.bat file. It will try to open a git-bash terminal with all variables set. Then you will need to fine a "make" binary. I used this 

https://gist.github.com/evanwill/0207876c3243bbb6863e65ec5dc3f058

Then you need to set a few variables telling the makefile where your Lua is. Look at win64.cmd to see what I used.

**Comment by sonoro1234** [comment]
After strugling with msvc I am gettin another undefined references so I am giving up.

> Then you will need to fine a "make" binary.

I meant building with nmake (msvc make) for which I can easily generate makefiles with cmake.

**Comment by diegonehab** [comment]
There are two independent problems here. One is how to build in general. 

I know what nmake is, and it is not compatible with make. So if you want to use the makefile we provide to build and install LuaSocket on Windows, you should not use nmake. If you want to use 
the projects or the makefile created by cmake, go for it. We don't use cmake and I am not sure I want to start maintaining it. 

I don't know how it finds the Lua binaries it need in order to link, or how those were built, and what compiler it is setup to use. There is no standard place for these to be installed on Windows. What I am saying is that if you know where they are, and if they were built using msvc, then you can use our project files or our makefile and they should work as well.

As for the inet_pton, I am not sure we should even care about anything older than Windows 7. 

Whoever is using a system that old must have very special needs and probably knows what they are doing. So if compile fails for them they better know how to set the define when building LuaSocket. What I am saying is that I didn't need to set it on Windows 7, which is what runs on the test box I have access to. I don't know about Windows 8 or 10.

**Comment by sonoro1234** [comment]
> I don't know how it finds the Lua binaries it need in order to link, or how those were built, and what compiler it is setup to use.

Just need to be provided in the command line of cmake as

```
cmake  -G"NMake Makefiles"  -DCMAKE_BUILD_TYPE="Release"  -DLUA_INCLUDE_DIR="C:/luaGL/sources/lua-5.1.5/src" -DLUA_LIBRARY="C:/build_Lua2SC_nmake/LuaJIT/lua51.lib" ../luasocket
```
-G is where you ask for a specific toolset MinGW, NMake or whatever

In a bundled compilation where I also compile lua and other stuff I just need to define where to point `LUA_INCLUDE_DIR` and `LUA_LIBRARY` and call add_subdirectory(luasocket)

**Comment by diegonehab** [comment]
There is a Lua.props file where you can set these thing before opening the project files. It should work. If you are using the makefile, then there is a similar set of variables that you can set in the command line where you invoke make. Do these things not work for you, or you simply prefer to use cmake?

**Comment by sonoro1234** [comment]
I work mainly with mingw without msys so that regular makefiles are not ok. This is why I use cmake to generate the mingw makefiles.

With the same cmake file I can compile with a lot of different toolsets ( see https://cmake.org/cmake/help/latest/manual/cmake-generators.7.html) and this is why I tried nmake also.
