### ISSUE TITLE
lua 5.3 out, it is compatible?

### ISSUE THREAD

**Issue by Neustradamus** [diegonehab/luasocket#124]
For information: http://www.lua.org/versions.html#5.3

**Comment by siffiejoe** [comment]
Almost. You just have to `#define` `LUA_COMPAT_APIINTCASTS` or `LUA_COMPAT_5_2` when you compile luasocket.

**Comment by andrewstarks** [comment]
Let me quote directly from the http://luarocks.org website:

### Quick start

#### Installing LuaRocks in a Unix system:

```bash
 wget http://luarocks.org/releases/luarocks-2.2.0.tar.gz
$ tar zxpf luarocks-2.2.0.tar.gz
$ cd luarocks-2.2.0
$ ./configure; sudo make bootstrap
$ sudo luarocks install luasocket
$ lua
Lua 5.3.0 Copyright (C) 1994-2015 Lua.org, PUC-Rio
> require "socket"
```
Did someone forget to paste:
```lua
error loading module 'socket.core' from file '/usr/local/lib/lua/5.3/socket/core.so':
	dlopen(/usr/local/lib/lua/5.3/socket/core.so, 6): Symbol not found: _luaL_checkint
  Referenced from: /usr/local/lib/lua/5.3/socket/core.so
  Expected in: dynamic lookup

stack traceback:
	[C]: in ?
	[C]: in function 'require'
	/usr/local/share/lua/5.3/socket.lua:12: in main chunk
	[C]: in function 'require'
	stdin:1: in main chunk
	[C]: in ?
```
?

I posted a pull request, which was bad and was closed. It's time someone who knows more C than i do to do the checks and fix the build without having to put in a command line compiler flag. Those should be for user options, not to make something basic work.

This kind of thing use to be very common in the Lua world. Thankfully, that's been changing and now this sort of thing stands out.

**Comment by siffiejoe** [comment]
The example on the Moonrocks site is obviously very bad since we don't have a working luasocket release for Lua 5.3 (or 5.2) yet. I guess somebody updated the example without checking that it actually works with the newest versions.

There are multiple ways to fix the `luaL_checkint` issue.

```C
#ifndef luaL_checkint
#define luaL_checkint(L, n) ((int)luaL_checkinteger(L,n))
#endif
```
or
```C
#ifndef LUA_COMPAT_APIINTCASTS
#define LUA_COMPAT_APIINTCASTS
#endif
#include <lauxlib.h>
```
or
```Lua
    -- ...
    defines = { "LUA_COMPAT_APIINTCASTS" },  -- in the rockspec
    -- ...
```
or just replacing `luaL_checkint` with `(int)luaL_checkinteger` (doesn't work on Lua 5.0).

IMHO, the best course of action depends on the Lua versions luasocket intends to support. The rockspec states `lua >= 5.1`, but in `mime.c` there's still `#include "compat-5.1.h"` (I don't know whether it actually still compiles/works on Lua 5.0). If we drop 5.0 support, we should do some refactoring (e.g. replacing `socket.skip` with `select`, which would already get rid of one of the two `luaL_checkint`s).

**Comment by andrewstarks** [comment]
My version of the fix was a broken version of

```C
#ifndef luaL_checkint
#define luaL_checkint(L, n) ((int)luaL_checkinteger(L,n))
#endif
```

Can we pretty please just do this? If it is suboptimal, it doesn't matter. It can get fixed for real-zies later. 

If there is a potential problem with it (breaks 5.0?) then that's different. But I can't see anything wrong with it and working is better than broken and it is just flat out broken.

I say that on the perhaps flawed understanding that LuaRocks is happy to install it with your Lua 5.3 libraries and as far as I can see, gives you no way to add the magic flag.

**Comment by siffiejoe** [comment]
I have sent an updated rockspec to the luarocks mailing list. However, you could add this flag to your local luarocks installation yourself using
```Lua
variables = {
  CC = "gcc -DLUA_COMPAT_APIINTCASTS"
}
```
in the luarocks configuration file ...

**Comment by andrewstarks** [comment]
Excellent. I do appreciate the pointer. I got this rolling on my own. 

[IMHO] My concern is was anchored in perception of quality, especially for newbies and for people new to Lua. Socket communication is one of the very first things people look for and so, like it or not, LuaSocket is pretty critical to Lua's reputation, generally.

Thank you, Phil!

**Comment by acmercyj** [comment]
how about  " Symbol not found: _lua_rotate " ?

**Comment by siffiejoe** [comment]
Looks like: compiled with the 5.3 headers but loaded by an older Lua interpreter (on Unix; on Windows: linked to an older Lua library).

**Comment by szym** [comment]
Was this fixed? I'm still experiencing ` Symbol not found: _luaL_checkint` with Lua 5.3.

**Comment by diegonehab** [comment]
Works for me. Did you figure it out?

**Comment by szym** [comment]
Sorry about the false report. The issue was in luasec.

**Comment by diegonehab** [comment]
No problem.

**Comment by TonyX19** [comment]
I replaced all luaL_checkint with (int)luaL_checkinteger. it does work. Thank you
