### ISSUE TITLE
Incorrect/incomplete docs for socket.try and protect

### ISSUE THREAD

**Issue by mpeterv** [diegonehab/luasocket#156]
It should be mentioned that socket.try wraps errors in a table (right now it says `otherwise, it calls error passing ret2` which is wrong). Likewise, it should be mentioned that socket.protect considers all tables "exceptions". (The fact that socket.protect silently drops tracebacks and that tables as errors are not supported is another bug?)

**Comment by diegonehab** [comment]
Can you post a pull request fixing the issue? Perhaps the best way to treat the problem would be to create a metatable, set it as upvalue to protect and try, then use the upvalue to set the metatable in wrap and check in unwrap.

**Comment by mpeterv** [comment]
@diegonehab would you accept it if I rewrote the try/protect module in Lua? It would be much clearer, I think, and need for lua_pcallk hacks would be gone. Considering luasocket's job is to do expensive networking syscalls, performance cost is negligible.

**Comment by siffiejoe** [comment]
@mpeterv: I already [tried once](https://github.com/diegonehab/luasocket/issues/112#issuecomment-62415654) ...

**Comment by diegonehab** [comment]
What exactly is the proposal? We need support for Lua 5.1, 5.2, and 5.3. I'm a bit rusty, but I believe the only way to make it work across a yield barrier in Lua 5.1 is to implement it in Lua using the complicated coroutine hack. Starting in 5.2, the C version can be used across yield barrier and the code is quite simple. It can be made more robust with the metatable idea I suggested. It can also be implemented in Lua and it would also be quite simple. I don't know that the performance impact would be, but am to agree that it wouldn't be too bad. We'd still have the problem with Lua 5.1, right?

**Comment by mpeterv** [comment]
The yield barrier problem is orthogonal to the original issue, and I don't have a strong opinion on whether luasocket should use coxpcall to work around it. My proposal is to do this, and do it in Lua for clarity:

> Perhaps the best way to treat the problem would be to create a metatable, set it as upvalue to protect and try, then use the upvalue to set the metatable in wrap and check in unwrap.

**Comment by siffiejoe** [comment]
Setting a special metatable on the error container table is a good idea to distinguish luasocket errors from other table-based ones. However setting/comparing a metatable with an upvalue is pretty easy in C as well, so it's not really a reason to use Lua. I already suggested implementing newtry/protect in Lua (because LuaJIT would benefit both in performance and in yieldability), but it was decided to go with the C implementation (see the thread I linked to above). Btw., I believe @moteus's [lua-try project][1] can also distinguish luasocket errors from other errors, but it's using a slightly different approach ...

  [1]: https://github.com/moteus/lua-try

**Comment by siffiejoe** [comment]
Ok, time for some micro benchmarks: I have a Lua implementation similar to [try.lua][1], but with the option to use `copcall` from the [coxpcall][2] module if it's loaded beforehand, and a C implementation similar to the one currently in LuaSocket but with the marker metatable to identify errors raised by `newtry()`. The "normal code path" test calls a `protect`ed Lua function one million times, and the `protect`ed Lua function calls `try( true)` (i.e. not raising any errors). The "failure code path" test is similar, but `try( nil, "failure" )` is called instead to raise a LuaSocket error. Here are the results (in seconds as measured by `os.clock()`, so smaller is better):

Lua 5.1:
normal code path, Lua, native pcall (no yield possible):  **0.377042**
normal code path, Lua, copcall:                                       **1.664628**
normal code path, C, (no yield possible):                         **0.230221**
failure code path, Lua, native pcall (no yield possible):  **0.841146**
failure code path, Lua, copcall:                                       **2.361381**
failure code path, C, (no yield possible):                         **0.387101**

LuaJIT:
normal code path, Lua:                              **0.000937**
normal code path, C, (no yield possible):   **0.155601**
failure code path, Lua:                               **2.855387**
failure code path, C, (no yield possible):    **3.348851**

Lua 5.2:
normal code path, Lua:  **0.373015**
normal code path, C:      **0.196271**
failure code path, Lua:   **0.865928**
failure code path, C:       **0.421179**

Lua 5.3:
normal code path, Lua:  **0.31963**
normal code path, C:      **0.210973**
failure code path, Lua:   **0.758624**
failure code path, C:       **0.426522**

So, the C version is usually about twice as fast as the Lua version. A yieldable `protect()` using [coxpcall][2] increases the runtime by a factor of 4. The Lua version *not* raising an error is very fast in LuaJIT. Raising errors in LuaJIT (both Lua code and C code) is *sloooooow*.

  [1]: https://github.com/hjelmeland/try-lua
  [2]: https://github.com/keplerproject/coxpcall

**Comment by diegonehab** [comment]
Awesome,  @siffiejoe. Good thing the failure case is rare. :) Shall we stick with the C version, add the metatable+upvalue check, and fix the documentation? Or shall we move to Lua? The Lua version is a lot  faster for LuaJIT and I agree it shouldn't make that much for the other implementations. I'm fine either way, so long as we don't introduce a bug in the process. :)

**Comment by siffiejoe** [comment]
If we are thinking about changing the implementation, I'd suggest also changing the [`pcall`][1] of the finalizer function to a regular call, so that you don't hide bugs in the finalizers.

  [1]:  https://github.com/diegonehab/luasocket/blob/e75444ccd1f30a3b5fbc7cec4a85e831bd0560ed/src/except.c#L53

**Comment by mpeterv** [comment]
Here is an implementation in Lua: #161.

**Comment by siffiejoe** [comment]
Looks good, and passes my tests as well. Performance is comparable to my previous benchmarks. Two questions remain:

1.  Should we support coxpcall when it's already loaded to enable yielding on PUC-Rio Lua 5.1? Something like `if type( copcall ) == "function" then pcall = copcall end` (`pcall` being a local here) would be sufficient.
2.  Do we really want to `pcall()` the finalizer? If it contains an error, the user will never know, because the error message is silently swallowed.

**Comment by diegonehab** [comment]
Merged #162. Let's move the discussion there.
