### ISSUE TITLE
identifier "SIGPIPE" is undefined

### ISSUE THREAD

**Issue by silentsnooc** [diegonehab/luasocket#198]
I am trying to compile luasocket-2.0.2 under Windows "as is" from the extracted archive but I am getting several errors regarding some macros which I assume should come with `signal.h`:

```
identifier "SIGPIPE" is undefined
identifier "F_GETFL" is undefined
identifier "O_NONBLOCK" is undefined
identifier "F_SETFL" is undefined
```

No idea what's missing here and I couldn't find anything to solve this.

Just a question aside: I know this is for Lua 5.2 but is there a chance this still works for Lua 5.0.1?

**Comment by ewestbrook** [comment]
Were you able to solve this?  If not, can you help with some information about your build environment, tools, and versions?

We're reviewing open items in preparation for a release.  If action is needed here, please add a comment.  Otherwise, this issue will be closed on or after 24-Feb-2019.

Thanks!
