### ISSUE TITLE
Bug in escaping/unescaping URLs

### ISSUE THREAD

**Issue by milani** [diegonehab/luasocket#201]
To reproduce the bug, try downloading a URL that includes `+` in the path, `+` as the real plus not a escaped space. The following code should demonstrate the bug:

```
local url = require("socket.url")
local request_url = "http://www.example.com/download/my%2bsample.file"
local result = url.build(url.parse(request_url))
print(result)
```

print statement should print the original URL, but instead it prints `http://www.example.com/download/my+bsample.file`.

**Comment by milani** [comment]
This problem appears when using `http.request` as you can see in `https://github.com/diegonehab/luasocket/blob/master/src/http.lua#L254` and `https://github.com/diegonehab/luasocket/blob/master/src/http.lua#L200`

**Comment by milani** [comment]
Seems removing `+` from protected_segments fixes the issue: https://github.com/diegonehab/luasocket/blob/master/src/url.lua#L56

**Comment by diegonehab** [comment]
Build() is not the inverse of parse(). Parse() removes escaping because when you use the results of parsing you typically want the unescaped values. Build() only adds escapes where they are needed. In your example, there is no need to escape the + sign because it is valid in within an URL segment. The RFC 2396 is very specific about which characters are allowed and we follow it to the letter. (Pun intended.)

**Comment by milani** [comment]
Yes, indivisually it is correct. But as a whole it is a bug. I can not use http.request with a URL that has escaped plus (℅2b) in it. When recieved on the server, it will be '+' which is interpreted as space. Instead, I should recieve the exact path I requested for.

**Comment by diegonehab** [comment]
This is just not true. The server must never change '+' to a space. As I said, '+' is a perfectly valid character in a path component of an URL. It is only translated to a space by CGI scripts themselves, not by the server, and that should only be done in the query component of the URL (what comes after the '?' sign). What server are you using?

**Comment by milani** [comment]
It is amazonaws, S3.

**Comment by diegonehab** [comment]
I meant what HTTP server...

**Comment by milani** [comment]
Amazon S3 is a static hosting, I upload files to it and it serves them. I'm not sure what it is because it is not something I can manage.

**Comment by diegonehab** [comment]
If you are using HTTP, there is an HTTP server somewhere that you are using. Any request will return headers. The headers will normally tell you what the server name is. Get all headers and dump them to screen using LuaSocket itself. Also, what is the exact URL you are trying to download?

**Comment by diegonehab** [comment]
See this:

https://forums.aws.amazon.com/thread.jspa?messageID=722673

It's a bug in their server. You can write code in Lua to protect your path segments. I am very reluctant to change LuaSocket to conform to buggy servers.

**Comment by milani** [comment]
I see. You are right.

**Comment by amir-sabbaghi** [comment]
@diegonehab How can I protect my path?
I have tried both `+` and `%2B` in my url but LuaSocket sends `+` for both. It automatically unescapes the url.
I know that LuaSocket is conforming to the standard but why it unescapes an already escaped url?

**Comment by diegonehab** [comment]
Because you are probably using the simplified interface to request() that receives the URL as a string, right? In that case, LuaSocket has to parse the URL itself, and it will do so following the RFC rules. You *may* be able to prevent LuaSocket from parsing the URL by using the general interface to request() that receives a table with all fields already defined. Something like this (untested)

    local t = {}
    local ret, code, headers, status = http.request{
        host = "http://www.example.com",
        port = 80,
        uri = "download/my%2bsample.file",
        sink = ltn12.sink.table(t)
    }
    print(table.concat(t))

The only problem I can foresee is if the server sends a redirect. In that case, LuaSocket will follow the redirect and will have to parse the location from the provided URL. This will, unfortunately, unescape the results. Can you try it?

**Comment by amir-sabbaghi** [comment]
it does not work:
```
/usr/lib/lua/socket/url.lua:186: attempt to index local 'parsed' (a nil value)
stack traceback:
        /usr/lib/lua/socket/url.lua:186: in function </usr/lib/lua/socket/url.lua:185>
        (tail call): ?
        /usr/lib/lua/ssl/https.lua:118: in function 'request'
        stdin:1: in main chunk
        [C]: ?
```

**Comment by amir-sabbaghi** [comment]
It needs a leading `/` in uri. It works with LuaSocket but still I cannot get it to work with LuaSec.

**Comment by diegonehab** [comment]
Maybe LuaSocket can try to preserve more of the URI when parsing so you can use the simple interface and so it can work with redirects. I'll see what I can do. But I don't control LuaSec.

**Comment by diegonehab** [comment]
@milani, can you try again with the most recent push?

**Comment by ewestbrook** [comment]
There has been a fair amount of URL path consistency work since this issue was posted.  Whether it's due to that or otherwise, in any case, the result seems to currently be:
```
$ lua <<EOF
> local url = require("socket.url")
> local request_url = "http://www.example.com/download/my%2bsample.file"
> local result = url.build(url.parse(request_url))
> print(result)
EOF
http://www.example.com/download/my%2bsample.file
```
which I believe was the desired result.  If I am mistaken, please let me know.

We're reviewing open items in preparation for a release.  If action is needed here, please add a comment.  Otherwise, this issue will be closed on or after 24-Feb-2019.

Thanks!

**Comment by milani** [comment]
Thank you for responding to this issue. To me, this is the correct behavior. Happy new release!
