### ISSUE TITLE
Build broken with LuaJIT

### ISSUE THREAD

**Issue by nzt4567** [diegonehab/luasocket#214]
Just to let you know, currently, both LuaJIT and luasocket define `luaL_setfuncs` which leads to link-time errors like 

```
/usr/local/lib/libluajit-5.1.a(lib_aux.o): In function `luaL_setfuncs':
/root/luajit-2.0/src/lib_aux.c:149: multiple definition of `luaL_setfuncs'
/usr/local/lib/lua/5.1/socket/libunix.a(compat.o):/root/luasocket/src/compat.c:7: first defined here
collect2: error: ld returned 1 exit status
```

Not sure if there is anything reasonable you can do about it though :(

**Comment by pracj3am** [comment]
Maybe you should not define `LUA_VERSION_NUM=501` :)

**Comment by diegonehab** [comment]
Did this solve the issue?

**Comment by mpeterv** [comment]
I have successfully installed luasocket from master and using latest released version (3.0rc-1) both with LuaJIT 2.0.5 and LuaJIT 2.1.0-beta3 using LuaRocks without any errors.

**Comment by siffiejoe** [comment]
Symbol lookup is different between static and dynamic linking. LuaJIT did add some symbols from Lua 5.2+, so with static linking you'll get in trouble if you also define those symbols for compatibility with older (PUC-Rio) Lua versions. Easiest workaround (if static linking is supposed to be supported) will probably be different names or a special prefix for the compatibility functions in LuaSocket, and maybe a conditional define so that you can still use the canonical names in the source.

**Comment by diegonehab** [comment]
Which function are we talking about? luaL_setfuncs? If so, why not simply change the #if to delete the definition when a LuaJIT version that defines it is detected? If somebody sends me a pull request I'll be happy to merge it.

**Comment by moteus** [comment]
I think problem in rockspec file.
On luarocks site scm rockspec does not include `compat.c` file
where this function defined for Lua 5.1/LuaJIT.

**Comment by ewestbrook** [comment]
No errors here using current master with LuaJIT 5.0.2.  Is this still a problem?  Does anyone have solid reproduction steps or versions to test?

We're reviewing open items in preparation for a release.  If action is needed here, please add a comment.  Otherwise, this issue will be closed on or after 24-Feb-2019.

Thanks!

**Comment by siffiejoe** [comment]
I'll look into it next weekend, but it doesn't seem anything has changed since then ...

**Comment by ewestbrook** [comment]
Thanks!  Please be sure you're using current master, and especially not LuaRocks, as the version available there is quite old (see #233).

**Comment by siffiejoe** [comment]
Issue still applies. How to reproduce:

Build for Linux using the include path for your LuaJIT installation:
```
make MYCFLAGS="-I/home/siffiejoe/.self/programs/luajit-2.1/include/luajit-2.1" linux
```
Compile and link the following sample program to the LuaSocket object files and the static LuaJIT library:
```
gcc -Wall -I/home/siffiejoe/.self/programs/luajit-2.1/include/luajit-2.1 -o foo foo.c *.o /home/siffiejoe/.self/programs/luajit-2.1/lib/libluajit-5.1.a -ldl -lm
```
Result:
```
/home/siffiejoe/.self/programs/luajit-2.1/lib/libluajit-5.1.a(ljamalg.o): In function `luaL_testudata':
ljamalg.c:(.text+0x4a150): multiple definition of `luaL_testudata'
compat.o:/home/siffiejoe/src/repos/luasocket/src/compat.c:23: first defined here
/home/siffiejoe/.self/programs/luajit-2.1/lib/libluajit-5.1.a(ljamalg.o): In function `luaL_setfuncs':
ljamalg.c:(.text+0x53ca0): multiple definition of `luaL_setfuncs'
compat.o:/home/siffiejoe/src/repos/luasocket/src/compat.c:7: first defined here
collect2: error: ld returned 1 exit status
```

Sample program:
```C
#include <stddef.h>
#include <stdlib.h>
#include <stdio.h>
#include <lua.h>
#include <lualib.h>
#include <lauxlib.h>

int luaopen_socket_core( lua_State* L );

int main( void ) {
  int rv = 0;
  int status = EXIT_FAILURE;
  lua_State* L = luaL_newstate();
  if( !L ) {
    fprintf( stderr, "Could not create Lua state!\n" );
    goto bailout;
  }
  lua_pushcfunction( L, luaopen_socket_core );
  lua_pushliteral( L, "socket.core" );
  rv = lua_pcall( L, 1, 1, 0 );
  if( rv ) {
    fprintf( stderr, "socket.core: %s\n", lua_tostring( L, -1 ) );
    goto bailout;
  }
  status = EXIT_SUCCESS;
bailout:
  if( L )
    lua_close( L );
  return status;
}
```

This pull request linked above is one trivial way to fix this.

**Comment by ewestbrook** [comment]
Thanks. I follow now. When Lua 5.2's functions aren't available, since we're just using our own functions anyway, we should use unique names to avoid collisions with similar efforts by LuaJIT (or anything else).  Doing it with the preprocessor means that the real Lua 5.2 functions will still be used when available.
