### ISSUE TITLE
Core file is missing

### ISSUE THREAD

**Issue by OmnissiahZelos** [diegonehab/luasocket#252]
The core file is missing

**Comment by ewestbrook** [comment]
Can you please elaborate?

**Comment by freeeyes** [comment]
The same as me.
> require "socket"
/usr/local/share/lua/5.1/./socket.lua:12: module 'socket.core' not found:
I searched issue. but nothing to told how to fix this.

**Comment by ewestbrook** [comment]
Are you still having this issue?

This could be caused by your `LUA_CPATH` environment variable not matching the installed location of `socket/core.so` (or `socket/core.dll` on Windows).  Please check that environment variable against the actual location of the installed file.  (If `LUA_CPATH` ends with two semicolons, you can also check the default paths, which can be revealed by printing the value of `package.cpath` from Lua.)

We're reviewing open items in preparation for a release.  If action is needed here, please add a comment.  Otherwise, this issue will be closed on or after 25-Feb-2019.

Thanks!

**Comment by freeeyes** [comment]
OK thanks，it's OK
