### ISSUE TITLE
The missing release 3.0

### ISSUE THREAD

**Issue by Neustradamus** [diegonehab/luasocket#93]
A lot of users/developers search the 3.0.

When it will be released?

**Comment by Neustradamus** [comment]
Any news?

**Comment by diegonehab** [comment]
Hey Neus,

I am going to talk to the other interested people to see if I can relinquish control over LuaSocket so that the community can release a version 3.0 if need be. What do you think about it? I have been very busy with my work, which is not at all related to LuaSocket, and I haven't been able to give it the attention it deserves.

Regards,
Diego
